import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f2",
        "error-container": "#ffdad6",
        "primary": "#0059bb",
        "outline-variant": "#c1c6d7",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary": "#b52330",
        "surface-variant": "#e5e2e1",
        "tertiary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#adc7ff",
        "on-tertiary-fixed": "#2f1500",
        "on-primary-container": "#fefcff",
        "tertiary": "#8d4b00",
        "surface": "#fcf9f8",
        "on-tertiary-container": "#fffbff",
        "surface-bright": "#fcf9f8",
        "secondary-container": "#ff5a5f",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed": "#410007",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "secondary-fixed": "#ffdad8",
        "primary-container": "#0070ea",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001a41",
        "background": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        "on-primary-fixed-variant": "#004493",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#adc7ff",
        "on-background": "#1b1c1c",
        "surface-tint": "#005bc0",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#92001b",
        "on-surface-variant": "#414754",
        "outline": "#717786",
        "secondary-fixed-dim": "#ffb3b0",
        "surface-dim": "#dcd9d9",
        "tertiary-container": "#b15f00",
        "on-secondary-container": "#60000e",
        "error": "#ba1a1a",
        "on-surface": "#1b1c1c",
        "surface-container": "#f0eded",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "lg": "48px",
        "md": "24px",
        "xl": "80px",
        "base": "8px",
        "gutter": "24px",
        "sm": "12px",
        "xs": "4px",
        "container-max": "1280px",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "nav-md": ["Playwrite DE SAS", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
